// Banco de dados de lasers dermatológicos (80+ dispositivos)
export const laserDatabase = [
  { name: "GentleMax Pro", manufacturer: "Candela", wavelength: "755nm + 1064nm", type: "Alexandrite + Nd:YAG" },
  { name: "Vbeam Pro", manufacturer: "Candela", wavelength: "595nm", type: "Pulsed Dye Laser (PDL)" },
  { name: "eCO2", manufacturer: "Syneron Candela", wavelength: "10600nm", type: "Fractional CO2" },
  { name: "Gentle Pro Series", manufacturer: "Candela", wavelength: "755nm + 1064nm", type: "Alexandrite/Nd:YAG" },
  { name: "Elite+", manufacturer: "Cynosure", wavelength: "755nm + 1064nm", type: "Alexandrite + Nd:YAG" },
  { name: "PicoSure", manufacturer: "Cynosure", wavelength: "755nm", type: "Picosecond Alexandrite" },
  { name: "PicoWay", manufacturer: "Candela/Cynosure", wavelength: "532nm + 1064nm", type: "Picosecond" },
  { name: "M22", manufacturer: "Lumenis", wavelength: "515-1200nm", type: "IPL + Laser Modules" },
  { name: "Stellar M22", manufacturer: "Lumenis", wavelength: "515-1200nm", type: "IPL + Laser" },
  { name: "UltraPulse", manufacturer: "Lumenis", wavelength: "10600nm", type: "CO2 Ablativo" },
  { name: "SP Dynamis", manufacturer: "Fotona", wavelength: "2940nm + 1064nm", type: "Er:YAG + Nd:YAG" },
  { name: "LightWalker", manufacturer: "Fotona", wavelength: "2940nm + 1064nm", type: "Er:YAG + Nd:YAG" },
  { name: "StarWalker", manufacturer: "Fotona", wavelength: "1064nm", type: "Picosecond Nd:YAG" },
  { name: "Joule", manufacturer: "Sciton", wavelength: "Variável", type: "Plataforma Modular" },
  { name: "ProFractional", manufacturer: "Sciton", wavelength: "2940nm", type: "Fractional Erbium" },
  { name: "excel V", manufacturer: "Cutera", wavelength: "532nm + 1064nm", type: "Vascular/Pigment" },
  { name: "Enlighten", manufacturer: "Cutera", wavelength: "532nm + 1064nm", type: "Pico/Nanosecond" },
  { name: "Enlighten Pico", manufacturer: "Cutera", wavelength: "532nm + 1064nm", type: "Picosecond" },
  { name: "Clarity II", manufacturer: "Lutronic", wavelength: "755nm + 1064nm", type: "Nd:YAG Platform" },
  { name: "Spectra", manufacturer: "Lutronic", wavelength: "532nm + 1064nm", type: "Q-switched/Pico" },
  { name: "Picoway", manufacturer: "Cynosure", wavelength: "532nm + 1064nm", type: "Picosecond" },
  { name: "Picoway Pro", manufacturer: "Cynosure", wavelength: "532nm + 1064nm", type: "Picosecond" },
  { name: "Q-Plus Evo", manufacturer: "Quanta System", wavelength: "532nm + 1064nm", type: "Q-switched" },
  { name: "SmartXide DOT", manufacturer: "DEKA", wavelength: "10600nm", type: "Fractional CO2" },
  { name: "SmartXide2", manufacturer: "DEKA", wavelength: "10600nm", type: "CO2 Fracionado" },
  { name: "Harmony XL Pro", manufacturer: "Alma", wavelength: "Variável", type: "Multi-aplicação" },
  { name: "Soprano ICE", manufacturer: "Alma", wavelength: "810nm", type: "Diodo" },
  { name: "Soprano ICE Platinum", manufacturer: "Alma", wavelength: "755nm + 810nm + 1064nm", type: "Triplo Diodo" },
  { name: "MeDioStar NeXT", manufacturer: "Asclepion", wavelength: "810nm", type: "Diodo" },
  { name: "LightSheer Quattro", manufacturer: "Lumenis", wavelength: "810nm", type: "Diodo" },
  { name: "SPLENDOR X", manufacturer: "Lumenis", wavelength: "755nm + 1064nm", type: "Alexandrite + Nd:YAG" },
  { name: "Clarity", manufacturer: "Lutronic", wavelength: "532nm + 1064nm", type: "Híbrido" },
  { name: "M22 ResurFX", manufacturer: "Lumenis", wavelength: "1550nm", type: "Non-ablativo Fracionado" },
  { name: "TimeWalker", manufacturer: "Fotona", wavelength: "2940nm + 1064nm", type: "Er:YAG + Nd:YAG" },
  { name: "Nd:YAG 1064nm", manufacturer: "Vários", wavelength: "1064nm", type: "Nd:YAG" },
  { name: "Alexandrite 755nm", manufacturer: "Vários", wavelength: "755nm", type: "Alexandrite" },
  { name: "Q-switched Nd:YAG", manufacturer: "Vários", wavelength: "532nm + 1064nm", type: "Q-switched" },
  { name: "Potenza", manufacturer: "Cynosure", wavelength: "RF", type: "RF Microneedling" },
  { name: "Lumecca", manufacturer: "InMode", wavelength: "515-1200nm", type: "IPL" },
  { name: "Morpheus8", manufacturer: "InMode", wavelength: "RF", type: "RF Microneedling" },
  { name: "NanoLaserPeel", manufacturer: "Sciton", wavelength: "2940nm", type: "Erbium Superficial" },
  { name: "MedLite C6", manufacturer: "Hoya ConBio", wavelength: "532nm + 1064nm", type: "Q-switched" },
  { name: "RevLite SI", manufacturer: "Cynosure", wavelength: "532nm + 1064nm", type: "Q-switched" },
  { name: "Spectra VRMIII", manufacturer: "Lutronic", wavelength: "532nm + 1064nm", type: "Q-switched" },
  { name: "Harmony", manufacturer: "Alma", wavelength: "Variável", type: "Plataforma Multi-módulos" },
  { name: "LightSheer Desire", manufacturer: "Lumenis", wavelength: "810nm", type: "Diodo" },
  { name: "Cutera Excel HR", manufacturer: "Cutera", wavelength: "755nm + 1064nm", type: "Vascular/Hair" },
  { name: "PicoGenesis", manufacturer: "Vários", wavelength: "532nm + 1064nm", type: "Picosecond" },
  { name: "Q-Switched Ruby", manufacturer: "Vários", wavelength: "694nm", type: "Ruby Q-switched" },
  { name: "Q-Switched Alexandrite", manufacturer: "Vários", wavelength: "755nm", type: "Q-switched" },
  { name: "LightPod Neo", manufacturer: "Aerolase", wavelength: "1064nm", type: "Nd:YAG" },
  { name: "Aerolase Neo", manufacturer: "Aerolase", wavelength: "1064nm", type: "Nd:YAG" },
  { name: "Lutronic Infini", manufacturer: "Lutronic", wavelength: "RF", type: "RF Microneedling" },
  { name: "Asclepion MeDioStar", manufacturer: "Asclepion", wavelength: "810nm", type: "Diodo" },
  { name: "Alma Harmony Pro", manufacturer: "Alma", wavelength: "Variável", type: "Plataforma" },
  { name: "Fraxel", manufacturer: "Solta Medical", wavelength: "1550nm", type: "Non-ablativo Fracionado" },
  { name: "Thermage", manufacturer: "Solta Medical", wavelength: "RF", type: "Radiofrequência" },
  { name: "Q-Plus C", manufacturer: "Quanta System", wavelength: "532nm + 755nm + 1064nm", type: "Q-switched/Alexandrite" },
  { name: "Fotona4D", manufacturer: "Fotona", wavelength: "2940nm + 1064nm", type: "Protocolo 4D" },
  { name: "PowerLase AT", manufacturer: "Fotona", wavelength: "1064nm", type: "Nd:YAG High-power" },
  { name: "CO2RE", manufacturer: "Syneron Candela", wavelength: "10600nm", type: "CO2 Fracionado" },
  { name: "Excel V+", manufacturer: "Cutera", wavelength: "532nm + 1064nm", type: "Vascular/Pigment" },
  { name: "Fotona NightLase", manufacturer: "Fotona", wavelength: "2940nm", type: "Protocolo Airway" },
  { name: "GentleLase Pro", manufacturer: "Candela", wavelength: "755nm", type: "Alexandrite" },
  { name: "ClearScan", manufacturer: "Vários", wavelength: "Variável", type: "Non-ablativo" },
  { name: "ClearLift", manufacturer: "Vários", wavelength: "1064nm", type: "Q-switched" },
  { name: "Laser Genesis", manufacturer: "Cutera", wavelength: "1064nm", type: "Non-ablativo Nd:YAG" },
  { name: "Broadband Light (BBL)", manufacturer: "Sciton", wavelength: "400-1400nm", type: "IPL Avançado" },
  { name: "Fotona Dynamis XP", manufacturer: "Fotona", wavelength: "2940nm + 1064nm", type: "Extended Platform" }
];

// Tipos de alvo expandidos para todos os procedimentos
export const targetTypes = [
  // Alvos pigmentares
  { value: "melanina_epidermica", label: "Melanina Epidérmica", procedures: ["Depilação", "Manchas"] },
  { value: "melanina_dermica", label: "Melanina Dérmica", procedures: ["Melasma", "Manchas profundas"] },
  { value: "pigmento_tatuagem", label: "Pigmento de Tatuagem", procedures: ["Remoção de tatuagem"] },
  { value: "melanossomas", label: "Melanossomas", procedures: ["Pigmentação"] },
  
  // Alvos vasculares
  { value: "hemoglobina_oxigenada", label: "Hemoglobina Oxigenada", procedures: ["Lesões vasculares"] },
  { value: "hemoglobina_desoxigenada", label: "Hemoglobina Desoxigenada", procedures: ["Veias"] },
  { value: "vasos_superficiais", label: "Vasos Superficiais", procedures: ["Rosácea", "Telangectasias"] },
  { value: "vasos_profundos", label: "Vasos Profundos", procedures: ["Varizes faciais"] },
  { value: "microvasculatura", label: "Microvasculatura", procedures: ["Vermelhidão difusa"] },
  
  // Alvos estruturais (colágeno/água)
  { value: "colageno_superficial", label: "Colágeno Superficial", procedures: ["Rejuvenescimento"] },
  { value: "colageno_profundo", label: "Colágeno Profundo", procedures: ["Lifting", "Firmeza"] },
  { value: "agua_epidermica", label: "Água Epidérmica", procedures: ["Resurfacing superficial"] },
  { value: "agua_dermica", label: "Água Dérmica", procedures: ["Resurfacing profundo"] },
  { value: "elastina", label: "Elastina", procedures: ["Flacidez"] },
  { value: "matriz_extracelular", label: "Matriz Extracelular", procedures: ["Remodelação"] },
  
  // Alvos celulares
  { value: "foliculo_piloso", label: "Folículo Piloso", procedures: ["Depilação"] },
  { value: "glandula_sebacea", label: "Glândula Sebácea", procedures: ["Acne", "Oleosidade"] },
  { value: "adipocitos", label: "Adipócitos", procedures: ["Redução de gordura"] },
  { value: "fibroblastos", label: "Fibroblastos", procedures: ["Rejuvenescimento"] },
  { value: "queratinócitos", label: "Queratinócitos", procedures: ["Textura"] },
  
  // Alvos de cicatrizes e acne
  { value: "tecido_cicatricial", label: "Tecido Cicatricial", procedures: ["Cicatrizes"] },
  { value: "fibrose", label: "Fibrose", procedures: ["Cicatrizes hipertróficas"] },
  { value: "lesoes_acneicas", label: "Lesões Acneicas", procedures: ["Acne ativa"] },
  
  // Alvos de lifting/firmeza
  { value: "smas", label: "SMAS (Sistema Músculo-Aponeurótico)", procedures: ["Lifting não invasivo"] },
  { value: "fascia_superficial", label: "Fáscia Superficial", procedures: ["Firmeza"] },
  { value: "derme_reticular", label: "Derme Reticular", procedures: ["Espessamento dérmico"] },
  
  // Outros alvos específicos
  { value: "nevus", label: "Nevus/Lesões Pigmentadas", procedures: ["Remoção de lesões"] },
  { value: "poros_dilatados", label: "Poros Dilatados", procedures: ["Refinamento de poros"] },
  { value: "estrias", label: "Estrias", procedures: ["Tratamento de estrias"] },
  { value: "celulite", label: "Celulite/Septos Fibrosos", procedures: ["Celulite"] }
];